import lexemesJson from './lexemes.json';
import rootsJson from './roots.json';

/** One vocabulary item. Generated by scripts/build-content.mjs — never edited. */
export interface Lexeme {
  /** The vocalised corpus lemma, and the persistence key. Stable forever. */
  id: string;
  /** What to show the learner. Differs from `id` only where the corpus lemma
   *  is an inflection fragment rather than a citable word. */
  ar: string;
  root: string | null;
  pos: string;
  gloss: string;
  /** Frequency rank in the Quran, 1 = most frequent. */
  rank: number;
  quranCount: number;
  level: number;
  /** Hand-authored gloss, not yet checked against a scholarly source. */
  unverified: boolean;
}

export interface Root {
  root: string;
  radicals: string[];
  lexemes: string[];
}

// The cast is checked at runtime by content.test.ts rather than by tsc: a
// 300-entry JSON literal is slow to type and the shape it must satisfy is the
// interface above, which the generator owns.
export const lexemes = lexemesJson as Lexeme[];
export const roots = rootsJson as Root[];

export const lexemeById = new Map(lexemes.map((l) => [l.id, l]));

/** root -> the lexeme ids that share it. The new-word block introduces a word
 *  together with its family rather than as an isolated fact. */
export const lexemesByRoot = new Map(roots.map((r) => [r.root, r.lexemes]));

/** Frequency order — the order the curriculum introduces words in. */
export const byRank = [...lexemes].sort((a, b) => a.rank - b.rank);
