// Regenerates content-inbox/manifest.json: one record per source file, keyed by
// sha256. Run it after dropping anything into content-inbox.
//
//   node scripts/manifest.mjs
//
// manifest.json is GENERATED — don't hand-edit it. Provenance for files fetched
// automatically lives in PROVENANCE below; anything else is marked user-supplied.
// Extraction results (written later by the content pipeline) are carried across
// runs by sha256, so re-running never loses them and never duplicates a source.

import { createHash } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { readFile, writeFile, readdir, stat } from 'node:fs/promises';
import { join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
// Optional arg lets the test point at a throwaway inbox instead of the real one.
const INBOX = process.argv[2] ? resolve(process.argv[2]) : join(ROOT, 'content-inbox');
const MANIFEST = join(INBOX, 'manifest.json');
const SKIP = new Set(['manifest.json', 'README.md', '.gitkeep']);

// Everything fetched on 2026-08-11. Licences are stated as published by the
// source; all of it is for personal study on one device.
const PROVENANCE = {
  'quran-morphology.txt': ['https://github.com/mustafa0x/quran-morphology', 'GNU GPL — Quranic Arabic Corpus 0.4 (Kais Dukes, 2011); Buckwalter converted to Arabic script by mustafa0x', 'Root + lemma + POS for all 130,030 Quran morphemes. The root atlas spine.'],
  'morphology-terms-ar.json': ['https://github.com/mustafa0x/quran-morphology', 'GNU GPL', 'Arabic names for the morphology tag set.'],
  'quran-morphology-README.md': ['https://github.com/mustafa0x/quran-morphology', 'GNU GPL', 'Documents the tag format.'],
  'quran-tanzil-uthmani.txt': ['https://tanzil.net/download/', 'Tanzil — free for non-commercial use, text must not be modified', 'Fully vocalised mushaf text. Source of truth for the harakat fade.'],
  'quran-tanzil-simple-vocalised.txt': ['https://tanzil.net/download/', 'Tanzil — free for non-commercial use', 'Simple orthography, vocalised.'],
  'quran-tanzil-simple-clean.txt': ['https://tanzil.net/download/', 'Tanzil — free for non-commercial use', 'No diacritics. The Level 4+ target rendering.'],
  'lane-quranic-roots.json': ['https://github.com/aliozdenisik/quran-arabic-roots-lane-lexicon', 'Lane definitions are public domain (1863–93); summaries are AI-generated by the repo author', '1,651 Quranic roots: verbatim Lane definitions, morphological forms with occurrence counts, Quran frequency. English summaries are UNVERIFIED.'],
  'lane-quranic-roots-README.md': ['https://github.com/aliozdenisik/quran-arabic-roots-lane-lexicon', 'see repo', 'Documents field meanings and how the AI summaries were produced.'],
  'lanes-lexicon-perseus-xml.zip': ['https://github.com/laneslexicon/lexicon_xml', 'Public domain (Lane, 1863–93); Perseus XML with community amendments', 'Complete Lane Lexicon in structured XML. Reference for Levels 5+.'],
  'kaikki-wiktionary-arabic.jsonl': ['https://kaikki.org/dictionary/Arabic/', 'CC BY-SA 4.0 / GFDL (Wiktionary)', 'Every Arabic Wiktionary entry as JSONL: senses, roots, forms, IPA. Gloss source for non-Quranic vocabulary.'],
  'quran-lemma-frequency-DERIVED.tsv': ['derived locally from quran-morphology.txt', 'inherits GNU GPL from source', 'GENERATED, not downloaded. Lemma frequency + cumulative coverage. Regenerate rather than edit.'],
  'wright-arabic-grammar-vol1.pdf': ['https://archive.org/details/in.ernet.dli.2015.44281', 'Public domain (Wright, 3rd ed. 1896)', 'Reference grammar vol 1.'],
  'wright-arabic-grammar-vol1.txt': ['https://archive.org/details/in.ernet.dli.2015.44281', 'Public domain', 'OCR text. Latin is reliable; Arabic OCR is not — do not extract Arabic from this.'],
  'wright-arabic-grammar-vol2.pdf': ['https://archive.org/details/in.ernet.dli.2015.31099', 'Public domain', 'Reference grammar vol 2 — syntax.'],
  'wright-arabic-grammar-vol2.txt': ['https://archive.org/details/in.ernet.dli.2015.31099', 'Public domain', 'OCR text. Same Arabic-OCR caveat.'],
  'madinah-durus-book1.pdf': ['https://archive.org/details/MadinaArabicBooks', 'Dr V. Abdur Rahim — freely distributed for study', 'Durus al-Lughah book 1. Arabic-only, no transliteration.'],
  'madinah-durus-book2.pdf': ['https://archive.org/details/MadinaArabicBooks', 'freely distributed for study', 'Durus al-Lughah book 2.'],
  'madinah-durus-book3.pdf': ['https://archive.org/details/MadinaArabicBooks', 'freely distributed for study', 'Durus al-Lughah book 3.'],
  'madinah-key-book1-en.pdf': ['https://archive.org/details/MadinaArabicBooks', 'freely distributed for study', 'English key — the gloss source for book 1 vocabulary.'],
  'madinah-key-book2-en.pdf': ['https://archive.org/details/MadinaArabicBooks', 'freely distributed for study', 'English key, book 2.'],
  'madinah-key-book3-en.pdf': ['https://archive.org/details/MadinaArabicBooks', 'freely distributed for study', 'English key, book 3.'],
  'ajurrumiyyah-matn-arabic.pdf': ['https://archive.org/details/ajouroumiyyah', 'Public domain (Ibn Ajurrum, d. 1323)', 'The classical grammar primer, Arabic matn.'],
  'ajurrumiyyah-matn-arabic.txt': ['https://archive.org/details/ajouroumiyyah', 'Public domain', 'OCR of the matn — Arabic OCR, verify before use.'],
  'ajurrumiyyah-en-hamza-yusuf.pdf': ['https://archive.org/details/al_ajurrumiyyah', 'Translation © Hamza Yusuf; archived copy', 'English translation of the matn.'],
  'ajurrumiyyah-tuhfa-saniyya-commentary-en.pdf': ['https://archive.org/details/al_ajurrumiyyah', 'archived copy', 'at-Tuhfa as-Saniyya commentary with English notes.'],
};

const sha256 = (path) => new Promise((res, rej) => {
  const h = createHash('sha256');
  createReadStream(path).on('data', (d) => h.update(d)).on('end', () => res(h.digest('hex'))).on('error', rej);
});

async function* walk(dir) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) yield* walk(p);
    else if (!SKIP.has(e.name)) yield p;
  }
}

// A missing manifest is the first run. A corrupt one must abort loudly: falling
// back to empty would silently discard every extraction record in it.
const raw = await readFile(MANIFEST, 'utf8').catch((err) => {
  if (err.code === 'ENOENT') return null;
  throw err;
});
let prev = { sources: [] };
if (raw !== null) {
  try {
    // Strip a UTF-8 BOM — PowerShell's `Set-Content -Encoding utf8` writes one
    // and JSON.parse rejects it.
    prev = JSON.parse(raw.replace(/^﻿/, ''));
  } catch (err) {
    throw new Error(`manifest.json exists but could not be parsed — refusing to overwrite it and lose extraction state.\n${err.message}`);
  }
}
const byHash = new Map(prev.sources.map((s) => [s.sha256, s]));

const sources = [];
for await (const path of walk(INBOX)) {
  const [hash, info] = await Promise.all([sha256(path), stat(path)]);
  const rel = relative(INBOX, path).split(sep).join('/');
  const name = rel.split('/').pop();
  const [source_url, licence, notes] = PROVENANCE[name] ?? [null, 'unknown — user supplied', ''];
  const old = byHash.get(hash);
  sources.push({
    path: rel,
    sha256: hash,
    bytes: info.size,
    added: old?.added ?? new Date().toISOString().slice(0, 10),
    source_url,
    licence,
    notes,
    // Carried across runs so re-importing never re-does work or loses corrections.
    extracted: old?.extracted ?? null,
  });
}
sources.sort((a, b) => a.path.localeCompare(b.path));

await writeFile(MANIFEST, JSON.stringify({ version: 1, generated: new Date().toISOString(), sources }, null, 2) + '\n');
const gb = sources.reduce((n, s) => n + s.bytes, 0) / 1e9;
console.log(`${sources.length} sources, ${gb.toFixed(2)} GB`);
console.log(`${sources.filter((s) => s.extracted).length} extracted, ${sources.filter((s) => !s.extracted).length} pending`);
const unknown = sources.filter((s) => !s.source_url);
if (unknown.length) console.log(`\nuser-supplied (no provenance recorded):\n${unknown.map((s) => '  ' + s.path).join('\n')}`);
